### ISSUE TITLE
MailGraph notification failed : SyntaxError: invalid json (at offset 1)

### ISSUE THREAD

**Issue by pqvindesland** [moudsen/mailGraph#38]
Hi

I have noticed one thing and this may or may not be a Mailgraph thing, if I configure my account to use Mailgraph and set off a new trigger then I get error "MailGraph notification failed : SyntaxError: invalid json (at offset 1)" so it looks like it's not getting the event id, if I change my account to use say normal html email media and set off the same trigger then I get the notification email.

But what I am puzzled with is that after rebooting the machine Mailgraph sends me a email saying that the Zabbix server has been restarted so it must be getting something, but not on some.

Does this make any sense and where could I start digging into this?

Regards
Per

**Comment by moudsen** [comment]
Did you try to trigger mailGraph thru the CLI?

**Comment by moudsen** [comment]
Have you noticed my troubleshooting page as well?
As you are not the only one that has contacted me for this I may add this specific error to the troubleshooting page.
Basically this happens when there is no event associated to the call to mailGraph.
If you try to test and when you do not enter actual values for the {EVENT.ID} and {DURATION} you will get the same error message.
When Zabbix calls the media type, it fills the macros with the actual related values for the event.
If this is not the actual issue, I suggest we switch on debugging and check a failed item in the generated logs?

**Comment by moudsen** [comment]
Considering how I could catch this one and explain in a better human manner. LOL

**Comment by moudsen** [comment]
Refactored code, now including pre- and postchecks on the given information.
The invalid json message should now no longer appear.
Releasing shortly after testing on Zabbix 5.4, 6.0 LTS and 6.4.

**Comment by moudsen** [comment]
Code now also includes the ability to leave eventId zero where mailGraph will pickup a random problem (the latest available) to report on. This will make it easier to test the mailGraph chain by CLI or within Zabbix :-).

**Comment by moudsen** [comment]
v2.11 released

**Comment by moudsen** [comment]
Can you please install this and share you experience?

**Comment by pqvindesland** [comment]
Hi

Yep I am trying to but when I try to import mailGraph.xml but it's failing with:

Cannot read XML: (4) Start tag expected, '<' not found [Line: 1 | Column: 1].

It seems to miss <?xml version="1.0" encoding="UTF-8"?> at the top could you please check?

**Comment by moudsen** [comment]
Strange. Working on it.

**Comment by moudsen** [comment]
Found it. Used the wrong export button unfortunately. Apologies for that.
Uploaded the right version just now. Can you pick it up and try?

**Comment by pqvindesland** [comment]
Yep works like a charm, but maybe change the https://zbx.puzzl.nl/zabbix/ in the template to https://company.com/zabbix/ ? just to anonymise it? :)

**Comment by pqvindesland** [comment]
So if I set off a test alert now I get: MailGraph notification failed : [MailGraph Webhook] Invalid duration? Integer required (set to zero if unknown)!

**Comment by moudsen** [comment]
LOL will remove some of my own settings indeed.
The test alert is correct: please set to zero to avoid.
So, in essence: set duration=0, eventid=0, itemid=0 and recipient to your mail address and you should be good to go ...

**Comment by moudsen** [comment]
Updated Troubleshooting section accordingly
https://github.com/moudsen/mailGraph/wiki/8--Troubleshooting

**Comment by moudsen** [comment]
While you are at it, I've resolved any message in mailGraph under PHP 7.4 and PHP 8.2 resulting in a very clean progress of mailGraph.
#36

**Comment by moudsen** [comment]
Released v2.12

**Comment by pqvindesland** [comment]
Hi with the change to phpmailer shouldn't the documentation also be updated  from composer require swiftmailer/swiftmailer to composer require phpmailer/phpmailer? just to avoid any confusion :) 

Also I notice that I am getting error  MailGraph notification failed: [MailGraph Webhook] Invalid duration? Integer required (set to zero if unknown)! regardless of what it's set in the config:

    "cli_itemId": 0,
    "cli_triggerId": 0,
    "cli_eventId": 0,
    "cli_duration": 0,
    
    And 
    
    
<img width="587" alt="Screenshot 2023-07-03 at 10 02 06" src="https://github.com/moudsen/mailGraph/assets/18611311/3bef1616-1f82-4c84-997e-3059108cdf8f">

Is that correct?

**Comment by moudsen** [comment]
Please change EVENT.DURATION and ITEM.ID to zero ('0') and set EVENT.ID to zero if you do not have an example Event available. When zero mailGraph will pickup the last event generated and take that forward.

On the CLI with the "test" command it should work just fine with all values set to zero. Let me check that at my end to be certain.

Yes, documentation updates are still underway and I definitely missed this one totally. Apologies for that.
Please use `composer require phpmailer/phpmailer` to pick up PHPMailer. You should be good to go.

**Comment by moudsen** [comment]
Verified that with all settings set to a 'zero' mailGraph v2.12 works fine?

To resolve your findings:
- CLI should work fine with the settings provided. 'php mailGraph.php test' should pickup a random eventId
- If testing via the GUI change EVENT.DURATION=0, ITEM.ID=0, EVENT.ID=0 and fill in your ALERT.SENDTO recipient mail address. Should also work.

Please let me know if that suffices.

**Comment by moudsen** [comment]
Documentation updated

**Comment by pqvindesland** [comment]
If I set 0 also in the gui then it works, but if I leave it as it came with say {EVENT.ID} then it doesn't work, with the settings below it works

<img width="613" alt="Screenshot 2023-07-03 at 14 37 14" src="https://github.com/moudsen/mailGraph/assets/18611311/67a7ed55-6311-4888-a84c-4594e7d28b41">

The config.json is configured like this:
    "cli_itemId": 0,
    "cli_triggerId": 0,
    "cli_eventId": 0,
    "cli_duration": 0,
    
    So yep it works but I was thrown off that the docs say leave say {EVENT.ID} it doesn't 
    
    A bit of a nit picking and I do apologise for that but I notice that the links to the Trigger ID, Item ID and Host ID doesn't work at the bottom of the emails:
<img width="336" alt="Screenshot 2023-07-03 at 14 43 33" src="https://github.com/moudsen/mailGraph/assets/18611311/011ce026-4945-4cf3-bf6e-6cd78babba3c">

**Comment by moudsen** [comment]
No problem! I will add an image to the documentation to better clarify this.
I will try to locate the reference to the EVENT.ID.
No apologies please! I will adjust as much as possible to make sure it's clear and unamiguous!

**Comment by moudsen** [comment]
Investigating the links

**Comment by moudsen** [comment]
Found 2 omissions (caused by Zabbix fundamental changes) and 1 missing (problem list reference).
Fixed and tested.
Released as v2.13

**Comment by moudsen** [comment]
Documentation updates for the troubleshooting pending

**Comment by pqvindesland** [comment]
I have done some extensive testing today since I am thinking of taking the installation into production soon, but I have noticed that on some errors I am still getting error: MailGraph notification failed : [MailGraph Webhook] No data received from mailGraph! Likely the event ID provided does not exist? Check mailGraph logging 

Now before you shoot me lol I have checked the troubleshooting page, and everything should be set correctly:
<img width="482" alt="Screenshot 2023-07-06 at 19 56 47" src="https://github.com/moudsen/mailGraph/assets/18611311/d62cbfd7-b90b-4411-815e-4badf056124b">

config.json
    "cli_itemId": 0,
    "cli_triggerId": 0,
    "cli_eventId": 0,
    "cli_duration": 0,

I checked in the action log and there is an event id;
<img width="1299" alt="Screenshot 2023-07-06 at 20 03 48" src="https://github.com/moudsen/mailGraph/assets/18611311/40e5a9a8-2da5-4920-8adc-420ae73b3c76">

Have you seen if it sometimes doesn't pick up event id's? it's a zabbix install that will mostly monitor web sites using the script from here: https://bestmonitoringtools.com/zabbix-web-monitoring-create-web-scenarios-with-examples/#Step_6_Automate_web_scenario_and_trigger_creation and it mailgraph doesn't seem to pickup does event id's which makes it difficult to go online :)

**Comment by moudsen** [comment]
Hi Per,

Appreciate your patience with me as well!
Can you please review if Zabbix did return any problem as I start to think of a scenario not taken into account at my end (yet): what if there are no active problems in the first place? That would explain it.
We can put this to the test: please use 285 for evenId instead of the zero and please let me know if that actually works as this would confirm that the 'get any problem' routine needs some more work (use a close event if no open ones ...). Piece of cake but just making sure we're not missing something else here.
I've not seen this in my live environment but hey, that actually has a lot of open problems in the first place :-).

Once confirmed I will review the 'get any random problem' routine accordingly.

Thx, Mark

**Comment by moudsen** [comment]
I am picking up from the API with parameter "recent=true" hence this may actually be the suspect routine.
Reading Zabbix API documentation.

**Comment by pqvindesland** [comment]
So I  ran it with "cli_eventId": 285, set and the output is as below the same from  media type:
<img width="960" alt="Screenshot 2023-07-06 at 21 28 18" src="https://github.com/moudsen/mailGraph/assets/18611311/07aab5fa-0aac-4010-8221-261b45130dfc">

The log output after I run it is:
Media type test log
00:00:00.000 [Debug] [MailGraph Webhook] Sending request: https://driftzabbix.intern.fremtind.no/mailGraph.php?{"itemId":0,"eventId":285,"recipient":"per.qvindesland@fremtind.no","baseURL":"https://driftzabbix.intern.fremtind.no/","duration":0,"graphWidth":"300","graphHeight":"120","subject":"{{ HOST_NAME|raw }}: ({{ EVENT_SEVERITY }}) {{ EVENT_NAME|raw }}","showLegend":"0","periods":"10m,4h,1d,7d","periods_headers":"Last 10 minutes,Last 4 hours,Last day,Last 7 days","infoTest":"Test"}
00:00:00.648 [Debug] [Mailgraph Webhook] Received response:! No response data received? 
00:00:00.648 [Unknown] MailGraph notification failed: [MailGraph Webhook] No data received from mailGraph! Likely the event ID provided does not exist? Check mailGraph logging

I´m sort of scratching my head here because I was pretty sure everything worked yesterday, but somehow it went pear shape today :( 


root@driftzabbix:/usr/share/zabbix# php mailGraph.php test
2023-07-06 19:25:13 : <<< mailGraph v2.13 >>>
2023-07-06 19:25:13 : # Invoked from CLI
2023-07-06 19:25:13 : # Data passed to MailGraph main routine and used for processing
{
    "itemId": 0,
    "eventId": 285,
    "recipient": "per.qvindesland@fremtind.no",
    "baseURL": "https:\/\/driftzabbix.intern.fremtind.no\/zabbix\/",
    "duration": 0,
    "subject": "[TEST] {{ HOST_NAME|raw }}:  ({{ EVENT_SEVERITY }}) {{ EVENT_NAME|raw }}",
    "period": "30m",
    "period_header": "Last 30 minutes",
    "debug": 1,
    "HTTPProxy": ""
}
2023-07-06 19:25:13 : # LOGIN to Zabbix
2023-07-06 19:25:13 : % postJSON: https://driftzabbix.intern.fremtind.no/zabbix/api_jsonrpc.php
2023-07-06 19:25:13 : > POST data: {"jsonrpc":"2.0","method":"user.login","params":{"username":"<masked>","password":"<masked>"},"id":1,"auth":null}
2023-07-06 19:25:13 : > Received 68 bytes
2023-07-06 19:25:13 : > Token = 46af2a06086f2e5a4bfb804d87c02861
2023-07-06 19:25:13 : # Record Zabbix API version
2023-07-06 19:25:13 : % postJSON: https://driftzabbix.intern.fremtind.no/zabbix/api_jsonrpc.php
2023-07-06 19:25:13 : > POST data: {"jsonrpc":"2.0","method":"apiinfo.version","params":[],"id":2}
2023-07-06 19:25:13 : > Received 42 bytes
2023-07-06 19:25:13 : > API version 6.0.19
2023-07-06 19:25:13 : # Retreiving EVENT information
2023-07-06 19:25:13 : % postJSON: https://driftzabbix.intern.fremtind.no/zabbix/api_jsonrpc.php
2023-07-06 19:25:13 : > POST data: {"jsonrpc":"2.0","method":"event.get","params":{"eventids":285,"output":"extend","selectRelatedObject":"extend","selectSuppressionData":"extend"},"auth":"46af2a06086f2e5a4bfb804d87c02861","id":3}
2023-07-06 19:25:13 : > Received 831 bytes
2023-07-06 19:25:13 : > Event data
{
    "jsonrpc": 2,
    "result": [
        {
            "eventid": 285,
            "source": 0,
            "object": 0,
            "objectid": 23390,
            "clock": 1688665866,
            "value": 1,
            "acknowledged": 0,
            "ns": 162798820,
            "name": "Website has ERROR (1): \"https:\/\/perq.no\"",
            "severity": 5,
            "r_eventid": 286,
            "c_eventid": 0,
            "correlationid": 0,
            "userid": 0,
            "opdata": "",
            "relatedObject": {
                "triggerid": 23390,
                "expression": "{33102}<>0 and {$WEBMON.ALARM.URL.DOWN}<>-1",
                "description": "Website has ERROR ({ITEM.LASTVALUE}): \"https:\/\/perq.no\"",
                "url": "",
                "status": 0,
                "value": 0,
                "priority": 5,
                "lastchange": 1688666346,
                "comments": "",
                "error": "",
                "templateid": 0,
                "type": 0,
                "state": 0,
                "flags": 0,
                "recovery_mode": 0,
                "recovery_expression": "",
                "correlation_mode": 0,
                "correlation_tag": "",
                "manual_close": 1,
                "opdata": "",
                "event_name": "",
                "uuid": ""
            },
            "suppression_data": [],
            "suppressed": 0,
            "urls": []
        }
    ],
    "id": 3
}
2023-07-06 19:25:13 : # Retrieve TRIGGER information
2023-07-06 19:25:13 : % postJSON: https://driftzabbix.intern.fremtind.no/zabbix/api_jsonrpc.php
2023-07-06 19:25:13 : > POST data: {"jsonrpc":"2.0","method":"trigger.get","params":{"triggerids":"23390","output":"extend","selectFunctions":"extend","selectTags":"extend","expandComment":1,"expandDescription":1,"expandExpression":1},"auth":"46af2a06086f2e5a4bfb804d87c02861","id":4}
2023-07-06 19:25:13 : > Received 614 bytes
2023-07-06 19:25:13 : > Trigger data
{
    "jsonrpc": 2,
    "result": [
        {
            "triggerid": 23390,
            "expression": "last(\/perq.no\/web.test.fail[\"https:\/\/perq.no [~]\"])<>0 and 4<>-1",
            "description": "Website has ERROR (0): \"https:\/\/perq.no\"",
            "url": "",
            "status": 0,
            "value": 0,
            "priority": 5,
            "lastchange": 1688666346,
            "comments": "",
            "error": "",
            "templateid": 0,
            "type": 0,
            "state": 0,
            "flags": 0,
            "recovery_mode": 0,
            "recovery_expression": "",
            "correlation_mode": 0,
            "correlation_tag": "",
            "manual_close": 1,
            "opdata": "",
            "event_name": "",
            "uuid": "",
            "functions": [
                {
                    "functionid": 33102,
                    "itemid": 45271,
                    "triggerid": 23390,
                    "parameter": "$",
                    "function": "last"
                }
            ],
            "tags": []
        }
    ],
    "id": 4
}
2023-07-06 19:25:13 : - Item ID taken from trigger (first) function = 45271
2023-07-06 19:25:13 : # Retrieve ITEM information
2023-07-06 19:25:13 : % postJSON: https://driftzabbix.intern.fremtind.no/zabbix/api_jsonrpc.php
2023-07-06 19:25:13 : > POST data: {"jsonrpc":"2.0","method":"item.get","params":{"itemids":"45271","output":"extend"},"auth":"46af2a06086f2e5a4bfb804d87c02861","id":5}
2023-07-06 19:25:14 : > Received 36 bytes
2023-07-06 19:25:14 : > Item data
{
    "jsonrpc": 2,
    "result": [],
    "id": 5
}
! No response data received?

**Comment by moudsen** [comment]
Definitely something else. Digging - give me a second.

**Comment by moudsen** [comment]
Hold on - itemId 45271 does no longer seem to exist as per the log?

Can you please verify in your system if this url works or returns an error: https://driftzabbix.intern.fremtind.no/zabbix/items.php?form=update&itemid=45271&context=host
(apologies - made a typo here - should be items.php)

(assembled it by hand, if it does not work pick any host item and change itemid to 45271)

**Comment by moudsen** [comment]
I may decide at this point to change the message in something that makes more sense.
Checking multiple events and complicating the source with this feels like a bit overkill while a new event/problem will just proof the functionality works.
Or would one care to receive messages from items that are deleted in the first place (LOL).

**Comment by pqvindesland** [comment]
<img width="566" alt="Screenshot 2023-07-06 at 21 44 17" src="https://github.com/moudsen/mailGraph/assets/18611311/8062182a-42a4-4ad0-b12d-928f668d7be6">

I got that message, if I try with another item id say https://driftzabbix.intern.fremtind.no/items.php?form=update&hostid=10084&itemid=44942&context=host I get the item, is that because it's missing the hostid ? 

Also in the action log it says itemId: {ITEM.ID] like the screenshot below, so I am a bit confused not if this is due to a shady setting from the registration script or if mailgraph isn't able to pull the information.

<img width="1532" alt="Screenshot 2023-07-06 at 21 55 21" src="https://github.com/moudsen/mailGraph/assets/18611311/a5172b2c-66f1-4ef3-a9fc-bce7451e90c0">

**Comment by moudsen** [comment]
You can remove the hostid part from any URL and it will simply work. At least at my end with Zabbix 5.4 and 6.0 LTS at hand?
The ItemId is not relevant for the process we are using at this point.
Can you please try by removing the hostid part and let me know?

**Comment by moudsen** [comment]
Pretty sure by now that the actual itemId at hand is missing (could be an auto-discovery item or a host that you've rebuild/re-discovered?).

**Comment by pqvindesland** [comment]
Yeah I am not really that keen on deleted hosts, oddly we never had this issue in my previous job where we also used Mailgraph and that installation is way way bigger then this one, if I had received notification from deleted hosts on that one then I would be forced to start drinking large amount of beers just to handle the frustration, that installation has about 120K of instances spread world wide all using mailgraph as media.

**Comment by moudsen** [comment]
Well in the previous version there was no auto-random-pickup of the eventId !!! LOL
Wow, honored to learn that my piece of work is taking on such environment! Appreciated!
(and will hunt down any issues with you to make sure it will run just perfectly!)

**Comment by pqvindesland** [comment]
Yeah you are right removing the hostid makes no difference the item id is still valid, damn so back to the drawing board.

Many thanks for looking into this at least now I know it's not mailgraph.

**Comment by moudsen** [comment]
What we can do here is that you revert back to using any known eventId for testing and not use the 'pick any event' function. That will definitely work any time.

**Comment by moudsen** [comment]
(as long as the item is not deleted somehow. LOLOL)

**Comment by moudsen** [comment]
I'm also still very keen on situations that mailGraph does not handle correctly and to find a way to deal with that, so please do keep bringing on any new issues you have out there!

**Comment by pqvindesland** [comment]
I can tell you that mailgraph was a key influencer to get Zabbix approved corporate wide, allowing a tech to view the stats of a server/switch and so on and be able to decide if the he/she had to do something was a key part, it saved hours of work and it looked pretty :)

**Comment by pqvindesland** [comment]
> What we can do here is that you revert back to using any known eventId for testing and not use the 'pick any event' function. That will definitely work any time.

If that is an option now then I would be more then happy to use it until I can get time to fix the discovery part, I may look much more into that script and sent the original developer the changes, but sadly my time as any other engineer so stretched that only around Christmas do I really have time for hard coding lol :)

**Comment by moudsen** [comment]
If I am around in Norway or you in Holland some time, let's agree to have a coffee and share strong stories!
I'm an Enterprise Architect developing tools like this for fun only and delighted to find and meet people in a similar state of unlimited happiness in our jobs!
Cheers and again honored that this tool seems to find its way around.

**Comment by eugenefeel** [comment]
@moudsen  Hello. I read this issue because i have problem with you project. When i exec cli test, I got email, but when i use button test or action in zabbix i have problem.
I noticed that eventid does not work.
Also in the action error I get the error
MailGraph notification failed : [MailGraph Webhook] Invalid duration? Integer required (set to zero if unknown)!
Help solve this problem

![ScreenShot-2023-08-11](https://github.com/moudsen/mailGraph/assets/139457476/11a2124c-1a43-408d-8f16-939e0bddd5a1)
![ScreenShot-2023-08-11](https://github.com/moudsen/mailGraph/assets/139457476/35a9df2e-f2fd-4be7-911f-7688a59a3e21)

**Comment by moudsen** [comment]
Can you please try with duration set to 1 or higher?

**Comment by eugenefeel** [comment]
To tell the truth, I tested it, but it did not work.

**Comment by eugenefeel** [comment]
To tell the truth, I tested it, but it did not work.

**Comment by eugenefeel** [comment]
I think you can reopen this issue

**Comment by moudsen** [comment]
Please raise a new ticket and I will look into it with you together.
This ticket is done.
